name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Checkout кода
      - name: Checkout code
        uses: actions/checkout@v4

      # Установка Python (если нужен)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Установка зависимостей (опционально)
      - name: Install dependencies
        run: |
          if (Test-Path requirements.txt) { python -m pip install --upgrade pip; pip install -r requirements.txt }

      # Проверка кода (базовая)
      - name: Lint code
        run: |
          if (Get-Command python -ErrorAction SilentlyContinue) { python -m py_compile *.py } else { echo "No Python files to check" }

      # Деплой на локальный каталог
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          $destination = "G:\Netology\deploy"
          New-Item -Path $destination -ItemType Directory -Force
          Copy-Item -Path . -Destination $destination -Recurse -Force
          echo "Deployed to $destination"
